# unit 1.2 - Binary net in PyTorch with manual weights

[![Open In Colab](https://colab.research.google.com/assets/colab-badge.svg)](https://githubtocolab.com/culurciello/deep-learning-course-source/blob/main/source/lectures/12-binary-net-pytorch-manual.ipynb)

Now we will learn what is a "proper" way to define this super simple AND neural network in PyTorch

In [41]:
import torch
from torch import nn
import torch.nn.functional as F

In [42]:
# Professional way to define AND model in pytorch:

class Logic_net(nn.Module): 
    def __init__(self): 
        super(Logic_net, self).__init__()
        self.l1 = nn.Linear(2, 1) # A simple layer with 2 inputs and 1 output

    def forward(self, x): 
        x = self.l1(x)
        return (x > 0).float() # Returns 1 or 0 based on input

model = Logic_net()

In [43]:
print(model.l1.weight)
print(model.l1.bias)

Parameter containing:
tensor([[ 0.3250, -0.1958]], requires_grad=True)
Parameter containing:
tensor([-0.1146], requires_grad=True)


In [44]:
# AND model weights:
model.l1.weight = nn.Parameter(torch.Tensor([[0.45,0.45]]))
model.l1.bias = nn.Parameter(torch.Tensor([-0.5]))

print(model.l1.weight)
print(model.l1.bias)

Parameter containing:
tensor([[0.4500, 0.4500]], requires_grad=True)
Parameter containing:
tensor([-0.5000], requires_grad=True)


In [45]:
# AND model test:
i1 = torch.Tensor([0,0])
o1 = model.forward(i1)
i2 = torch.Tensor([0,1])
o2 = model(i2)
i3 = torch.Tensor([1,0])
o3 = model(i3)
i4 = torch.Tensor([1,1])
o4 = model(i4)

print("out:", o1.item(),o2.item(),o3.item(),o4.item())

out: 0.0 0.0 0.0 1.0


In [46]:
# Easier way to define AND model since we are using only single perceptron:

model = torch.nn.Sequential(
    torch.nn.Linear(2, 1, bias = True),
    #torch.nn.ReLU()
)

# print(model)
# print(model[0].weight)

# a AND model weights:
model[0].weight = nn.Parameter(torch.Tensor([[1,1]]))
model[0].bias = nn.Parameter(torch.Tensor([-1.5]))

# AND model test:
i1 = torch.Tensor([0,0])
o1 = (model(i1) > 0).float()
i2 = torch.Tensor([0,1])
o2 = (model(i2) > 0).float()
i3 = torch.Tensor([1,0])
o3 = (model(i3) > 0).float()
i4 = torch.Tensor([1,1])
o4 = (model(i4) > 0).float()

print("out:", o1.item(),o2.item(),o3.item(),o4.item())

out: 0.0 0.0 0.0 1.0


## HOMEWORK

Try to make the XOR or XNOR neural network on your own.

Tip: think about decomposing the XOR function: XOR(x1,x2) = (x1 AND NOT x2) OR (NOT x1 AND x2)

Can it be solved with 1 neuron?

In [47]:
# Define the XOR neural network
class XORNet(nn.Module):
    def __init__(self):
        super(XORNet, self).__init__()
        
        # Define the layers
        self.l1 = nn.Linear(2, 2)  # 2 inputs -> 2 hidden neurons
        self.l2 = nn.Linear(2, 1) # 2 hidden neurons -> 1 output
        
    
    def forward(self, x):
        # Forward pass: hidden layer -> activation -> output layer
        x = torch.sigmoid(self.l1(x))  # Apply sigmoid activation in the hidden layer
        x = torch.sigmoid(self.l2(x))  # Apply sigmoid activation in the output layer
        return x

# Instantiate the model
model = XORNet()
# Set pre-defined weights for the hidden layer
model.l1.weight = nn.Parameter(torch.Tensor([[-8.0, -8.0], [-9.0, -9.0]]))  # Predefined weights
model.l1.bias = nn.Parameter(torch.Tensor([11.0, 4.0]))  # Predefined biases

# Set pre-defined weights for the output layer
model.l2.weight = nn.Parameter(torch.Tensor([[13.0, -13.0]]))  # Predefined weights
model.l2.bias = nn.Parameter(torch.Tensor([-6.0]))  # Predefined bias

In [48]:
# Example inputs for XOR (truth table)
inputs = torch.Tensor([[0, 0], [0, 1], [1, 0], [1, 1]])

# Perform the forward pass
outputs = model(inputs)

# Print the results
print("Inputs:")
print(inputs)
print("\nPredicted Outputs:")
print(outputs.detach())

for i in range(len(inputs)):
    print(f"Input: {inputs[i]}, Output: {(outputs[i]> 0.5).float()}")

Inputs:
tensor([[0., 0.],
        [0., 1.],
        [1., 0.],
        [1., 1.]])

Predicted Outputs:
tensor([[0.0031],
        [0.9982],
        [0.9982],
        [0.0027]])
Input: tensor([0., 0.]), Output: tensor([0.])
Input: tensor([0., 1.]), Output: tensor([1.])
Input: tensor([1., 0.]), Output: tensor([1.])
Input: tensor([1., 1.]), Output: tensor([0.])


How did we calculate these Weights and Biases??