# unit 1.3 - Binary network PyTorch Training 

[![Open In Colab](https://colab.research.google.com/assets/colab-badge.svg)](https://githubtocolab.com/culurciello/deep-learning-course-source/blob/main/source/lectures/13-binary-net-pytorch.ipynb)

Here we will use Pytorch to train a neural network for the AND function

Train = find the values of the weights automatically / no trial and error!

For training, we will need a lot of examples. Examples are in the form of: {input, desired_output} 

desired_output is also called ground_truth or label


In [10]:
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim

class Net(nn.Module):
    def __init__(self):
        super(Net, self).__init__()
        self.l1 = nn.Linear(2, 2)
        self.l2 = nn.Linear(2, 1)

    def forward(self, x):
        x = F.relu(self.l1(x))
        output = self.l2(x)
        return output

This create a neural network in pytorch in the "proper" way. You can do this in many ways, but this is one way professionals in AI use!

NOW!!!!

To train we will use an algorihtm called "gradient descent"

We define a "train" function that can:
- take all the examples we have
- run the network on inputs
- compare the network output to the ground truth
- compute a measure of error
- back-propagate the error
- adjust the weights
- repeat for all samples in dataset

network = neural network to train

Optimizer = grandient descent algorithm to update the weights

train _loader = loads examples from a dataset / database


In [11]:
def train(model, train_loader, optimizer, epoch):
    model.train()
    for batch_idx, (data, target) in enumerate(train_loader):
        data = torch.Tensor(data)
        target = torch.Tensor([target])
#         print(batch_idx, data, target)
        optimizer.zero_grad()

        # forward pass
        output = model(data)
#         loss = 1/2*(output-target).pow(2).sum()
        loss = F.mse_loss(output, target)
        
        # backward pass
#         for p in model.parameters():
#             p.grad = None

        loss.backward()
        optimizer.step()

        # weight update:
#         lr = 0.1
#         for p in model.parameters():
#             p.data += -lr * p.grad

        if batch_idx % 4 == 0:
            print('Train Epoch: {} [{}/{} ({:.0f}%)]\tLoss: {:.6f}'.format(
                epoch, batch_idx * len(data), len(train_loader),
                100. * batch_idx / len(train_loader), loss.item()))
                
model = Net()
optimizer = optim.Adam(model.parameters(), lr=1e-1)

# dataset: logic AND!
train_loader = [((0,0),0),((0,1),0),((1,0),0),((1,1),1)] # inputs, outputs examples (4)

for epoch in range(1, 20):
    train(model, train_loader, optimizer, epoch)

Train Epoch: 1 [0/4 (0%)]	Loss: 0.553271
Train Epoch: 2 [0/4 (0%)]	Loss: 0.058785
Train Epoch: 3 [0/4 (0%)]	Loss: 0.044013
Train Epoch: 4 [0/4 (0%)]	Loss: 0.099825
Train Epoch: 5 [0/4 (0%)]	Loss: 0.020945
Train Epoch: 6 [0/4 (0%)]	Loss: 0.000249
Train Epoch: 7 [0/4 (0%)]	Loss: 0.001792
Train Epoch: 8 [0/4 (0%)]	Loss: 0.000732
Train Epoch: 9 [0/4 (0%)]	Loss: 0.000000
Train Epoch: 10 [0/4 (0%)]	Loss: 0.000010
Train Epoch: 11 [0/4 (0%)]	Loss: 0.000794
Train Epoch: 12 [0/4 (0%)]	Loss: 0.006000
Train Epoch: 13 [0/4 (0%)]	Loss: 0.013697
Train Epoch: 14 [0/4 (0%)]	Loss: 0.018032
Train Epoch: 15 [0/4 (0%)]	Loss: 0.019104
Train Epoch: 16 [0/4 (0%)]	Loss: 0.020696
Train Epoch: 17 [0/4 (0%)]	Loss: 0.023420
Train Epoch: 18 [0/4 (0%)]	Loss: 0.023930
Train Epoch: 19 [0/4 (0%)]	Loss: 0.020412


In [12]:
# test model trained on logic AND:

model.eval()

with torch.no_grad():
    inp = torch.Tensor([(0,0)])
    o1 = model(inp)
    inp = torch.Tensor([(0,1)])
    o2 = model(inp)
    inp = torch.Tensor([(1,0)])
    o3 = model(inp)
    inp = torch.Tensor([(1,1)])
    o4 = model(inp)
    
o1,o2,o3,o4

(tensor([[-0.1246]]),
 tensor([[0.0555]]),
 tensor([[0.0539]]),
 tensor([[0.9682]]))

Now we can compare the learned weights with the manual ones we used before

In [13]:

# print learned weights:
print('model.l1.weight:', model.l1.weight.data)
print('model.l1.bias:', model.l1.bias.data)
print('model.l2.weight:', model.l2.weight.data)
print('model.l2.bias:', model.l2.bias.data)


# or more compactly - print learned weights:
# print('learned weights:')
# for p in model.parameters():
    # print(p.data)

model.l1.weight: tensor([[ 0.9563,  0.9579],
        [-0.2765, -0.7017]])
model.l1.bias: tensor([-0.7692, -0.7161])
model.l2.weight: tensor([[0.9545, 0.0038]])
model.l2.bias: tensor([-0.1246])


Here the interesting portions to dig deeper are:

- what is the [loss](https://pytorch.org/docs/stable/nn.html#loss-functions)?
- what is the [optimizer](https://pytorch.org/docs/stable/optim.html)?



HOW DO I LEARN MORE on gradient descent?

To go forward, you have some options:

1- learn to use pytorch optimization as is

- for this you are done!

2- learn more details about back-propagation but just enough

- See [this step-by-step example](https://mattmazur.com/2015/03/17/a-step-by-step-backpropagation-example/)

3- learn how backpropagation in pytorch works

- This [series is amazing](https://www.youtube.com/watch?v=VMj-3S1tku0&list=PLAqhIrjkxbuWI23v9cThsA9GvCAUhRvKZ&index=1)